### ISSUE TITLE
Added drag and drop pdf file function to the software

### ISSUE THREAD

**Issue by phuongnamhoangde** [raydac/pdf-image-remover#1]
Please add function: **drag and drop files directly into the software.**

This will reduce the time spent opening and searching for files.

Hopefully the above function will be updated soon. Thank you very much !

**Comment by raydac** [comment]
you can try https://github.com/raydac/pdf-image-remover/releases/tag/1.1.1-S

**Comment by phuongnamhoangde** [comment]
It works fine. Thank you very much
